import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalFetchInterceptor } from "@/components/GlobalFetchInterceptor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalErrorProvider } from "../components/GlobalErrorDisplay";
import { SWRProvider } from "../components/SWRProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalErrorProvider> {/* Wrap with GlobalErrorProvider */}
          <SWRProvider>{children}</SWRProvider>
        </GlobalErrorProvider>
      </body>
    </html>
  );
}
